// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnrxykbxhvjjvdwnbiar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ucnh5a2J4aHZqanZkd25iaWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDg3NTksImV4cCI6MjA2NjE4NDc1OX0.pDpnynNpQB9FNBFnBOnfB-c9YtbWvv8SMmaNKHUvCPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);